#!/bin/bash

mygpuContID="10de:2482"
mygpuPATH="0000:09:00.0"
mydriver="nvidia"
vmname="win10"

txtblk='\e[0;30m' 	# Black - Regular
txtred='\e[0;31m' 	# Red
txtgrn='\e[0;32m' 	# Green
txtblu='\e[0;34m'	# Blue
txtyel='\033[1;93m' # yello
txtrst='\e[0m' 		# Text Reset

memfree(){
	[ $(grep MemAvailable /proc/meminfo|cut -d: -f2|grep "[0-9]*" -o) -gt $(($1*1000000)) ]
}

swapdriver(){
	mygpuPATH=$1
	driverToBind=$2

	#verifier si le driver est deja bind
	[[ "$(lspci -s $mygpuPATH -k 2> /dev/null)" =~ "Kernel driver in use: $driverToBind" ]] && echo -e $txtblu"driver déja monter"$txtrst && return 0

	#s'asure que rien ne tourne sur la carte
	lsof /dev/nvidia1 | xargs -r kill -SIGKILL


	#chemain du driver est unbine donc connaitre le old drivezr
	if [[ -e "/sys/bus/pci/devices/${mygpuPATH}/driver" ]]
	then
		#unbind du driver
		sudo echo ${mygpuPATH} > /sys/bus/pci/devices/${mygpuPATH}/driver/unbind
	else
		echo -e "${txtyel}driver deja retirer !"$txtrst
	fi
	#bind new driver
	sudo echo ${mygpuPATH} > /sys/bus/pci/drivers/${driverToBind}/bind || { echo -e $txtred driver indisponible/inexistant ; exit 1;}

	#check unbind
	[[ "$(lspci -s $mygpuPATH -k 2> /dev/null)" =~ "Kernel driver in use: $driverToBind" ]] && echo -e $txtgrn"driver monter"$txtrst || { echo -e $txtred"driver non monter" ; exit 2 ;}
}

startvm(){
	#check ram usage
	memfree 8 || {echo -e $txtred pas assez de mémoir $txtrst; exit 4}
	sudo virsh start $1 && { echo -e $txtgrn"vm on"$txtrst;looking;}|| { echo -e $txtred" soucis"$txtrst;exit 3;}
}

stopvm(){
										 #trouver plus extreme
	sudo virsh shutdown $1 && echo -e $txtgrn"vm off"$txtrst || { echo -e $txtred" soucis"$txtrst;exit 3;}
}




####met de la charge au pc

load_pc(){
	#start sheep-it
	memfree 2 &&  konsole --profile CUL --new-tab -e "sheepit-client"&
	#start eth
	swapdriver $mygpuPATH nvidia && konsole --profile Judy --new-tab -e "ethminer --cu-devices 0 -P $ETHPOOL"&
		#--list-profile-properties	
}

unload_pc(){
	echo ok
	jobs
}

##main

case $1 in
   "swap")
      swapdriver $mygpuPATH $2
      ;;
   "start")
		swapdriver $mygpuPATH vfio-pci && startvm $vmname
      ;;
   "stop")
      stopvm $vmname && swapdriver $mygpuPATH nvidia
      ;;
   "load")
      load_vm
      ;;
   "unload")
      unload_pc
      ;;
   *)
     echo -e $txtyel"pas bonne option:\n"$txtblu"\t- swap\n\t- start\n\t- stop"
     ;;
esac



